schedule:
  - minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    day_of_week: "*"
    subreddits:
      - all
      - csMajors
      - cscareerquestions
      - leagueoflegends
      - iOSProgramming
      - FirstTimeHomeBuyer